### ISSUE TITLE
Support for .changes() and .on()

### ISSUE THREAD

**Issue by JustinDrake** [flimzy/go-pouchdb#42]
The README states as a TODO

> Add support for Changes Feeds (for use by changes() and live replication)

This is a heads-up that @jackkleeman and I want this feature! 👍  Is there a particular difficulty implementing `changes()`?

**Comment by flimzy** [comment]
> Is there a particular difficulty implementing changes()?

Not that I know of. I just haven't used it yet, so haven't had a handy way of testing it.

**Comment by flimzy** [comment]
I welcome your feedback on #43 , which adds support for event listeners on `created` and `destroyed` events.

I'm especially interested in your thoughts on the API, as there's no clear "best practice" for implementing JavaScript event listeners in Go.

I could, for instance, use a simple `On()` method, which takes an event name and function as an argument, as JavaScript does.  My fear, however, was that this might be too flexible; there are only ever two events (unless plugins are used, perhaps?), and they take a very specific function signature.  So I opted to support only that.  But since I don't actually use this interface, it may be that I've overlooked something.

**Comment by jackkleeman** [comment]
I agree, because the signatures are different to other instances of on() in the api ([which relate to changes()](https://pouchdb.com/api.html#changes)), there may as well be specific functions for each event type.

**Comment by flimzy** [comment]
Very well. I've merged that.

The harder problem is going to be how to implement the Changes interface. It's a rather complex API, and it's not at all obvious to me how best to wrap it in Go.

I'll try to implement the Changes API in [github.com/fjl/go-couchdb](https://godoc.org/github.com/fjl/go-couchdb).

**Comment by flimzy** [comment]
It looks like fjl/go-couchdb has it's on way of handling create/destroy events, too.  I may opt for that method in place of the OnCreate/OnDestroy methods I just created.  So please keep that in mind before getting too attached to the new API.

**Comment by jackkleeman** [comment]
No problem.

**Comment by flimzy** [comment]
I've begun work on supporting ChangesFeed, as you can see in PR #45. There are no known bugs at the moment, but it's also not very fully tested.  It may be a while (1-2 weeks?) before I'm able to make a lot more progress. Feel free to play with that branch in the meantime, test it for your needs, or even submit your own PR, if you wish.

**Comment by JustinDrake** [comment]
Thanks @flimzy 👍

**Comment by flimzy** [comment]
Full support for the changes feed now exists in [Kivik](https://github.com/flimzy/kivik), which supersedes this package, so I'm going to close this issue.
